### ISSUE TITLE
hello issue

### ISSUE THREAD

**Issue by goutham9032** [dabbacompny/hellodude#3]
@shivam-deepcompute The performance on test8 appears to have dropped by about 5% owing to per-word alpha computation. that is not bad at all. need your help now to test quality of vector space across perword and global on tex8. Also, currently I supported only in Skipgram with HS. If we find that this works well, we'll have to support for others too.

**Comment by goutham9032** [comment]
i am commenting

**Comment by goutham9032** [comment]
i am commented and closed the issue

**Comment by shivam-deepcompute** [comment]
@goutham9032 is this some kind of test?

**Comment by goutham9032** [comment]
@shivam-deepcompute The performance on test8 appears to have dropped by about 5% owing to per-word alpha computation. that is not bad at all. need your help now to test quality of vector space across perword and global on tex8. Also, currently I supported only in Skipgram with HS. If we find that this works well, we'll have to support for others too.
